name: Update and Build Kernel
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable # Use Nix unstable - ensure this aligns with flake!

      - uses: cachix/cachix-action@v14
        with:
          name: kernel-zenplus # Repo Name for Cachix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          useDaemon: false

      - name: Update Flake
        run: nix flake update

      - name: Build Linux Kernel
        run: nix build . --print-build-logs --cores 0 --max-jobs 1 # Use all cores, hopefully speeding up builds

      - name: Commit changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: (Automated) update flake.lock"
          push_options: '--force-with-lease'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: (Automated) update to ${{ steps.meta.outputs.version }} (${{ steps.meta.outputs.date }})"
          file_pattern: 'flake.lock'
          push_options: '--force-with-lease'

      - name: Publish GH Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Generate date in YYYY.MM.DD format
          RELEASE_DATE=$(date +'%Y.%m.%d')
          
          # Create the release
          gh release create "$RELEASE_DATE" \
            --title "Kernel Build - $RELEASE_DATE" \
            --generate-release-notes \
            --notes "Automated Linux ZenPlus build as of $RELEASE_DATE"